# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (15)
# #########################################################################

class AttachmentInput(BaseModel):
    # AttachmentInput
    # 
    # Purpose
    # -------
    # Represents one task-relevant attachment available to the root planner for
    # the current turn.
    # 
    # Fields
    # ------
    # - attachment_name: original filename or host-generated attachment label.
    # - mime_type: MIME type if known.
    # - source_ref: host-visible reference such as a URL, local path, or opaque
    # attachment handle.
    # - summary: optional host-provided summary or extracted preview.
    # 
    # Invariants
    # ----------
    # - source_ref should be non-empty when an attachment exists.
    # 
    # Notes
    # -----
    # The planner may use attachment metadata to decide whether to call
    # ingestion or parsing tools rather than reading raw file bytes directly.

    attachment_name: typing.Optional[str] = Field(default=None, description='Original filename or attachment label')
    mime_type: typing.Optional[str] = Field(default=None, description='Attachment MIME type if known')
    source_ref: typing.Optional[str] = Field(default=None, description='Host-visible attachment reference or handle')
    summary: typing.Optional[str] = Field(default=None, description='Optional host-provided summary or preview')

class BindingSnapshot(BaseModel):
    # BindingSnapshot
    # 
    # Purpose
    # -------
    # Represents one current runtime binding summarized for planner
    # consumption.
    # 
    # Fields
    # ------
    # - binding_name: runtime binding name currently available.
    # - value_summary: host-generated compact summary of the current value.
    # 
    # Invariants
    # ----------
    # - value_summary should be descriptive enough to support planning without
    # dumping unbounded runtime state.
    # 
    # Notes
    # -----
    # This is a summary surface for planning, not a lossless serialization of
    # runtime values.

    binding_name: typing.Optional[str] = Field(default=None, description='Name of a runtime binding currently available')
    value_summary: typing.Optional[str] = Field(default=None, description='Compact host summary of the binding value')

class ExprNode(BaseModel):
    # ExprNode
    # 
    # Purpose
    # -------
    # Represents one tagged expression node in the root planner's BAML mirror
    # of the REPL DSL.
    # 
    # Fields
    # ------
    # - expr_kind: concrete expression variant tag.
    # - literal_value: payload for literal expressions.
    # - ref_name: binding name for REF expressions.
    # - task_ref_name: task-handle name for TASK_REF expressions.
    # - object_fields: named field list for OBJECT expressions.
    # - list_values: ordered element list for LIST expressions.
    # - lhs_expr: left-hand operand for COMPARISON and LOGICAL expressions.
    # - rhs_expr: right-hand operand for COMPARISON and LOGICAL expressions.
    # - comparison_operator: operator for COMPARISON expressions.
    # - logical_operator: operator for LOGICAL expressions.
    # - unary_operator: operator for UNARY expressions.
    # - operand_expr: operand for UNARY expressions.
    # 
    # Invariants
    # ----------
    # - expr_kind determines which payload fields should be populated.
    # 
    # Notes
    # -----
    # Host code should validate consistency between expr_kind and populated
    # fields before translating to the Python AST.

    expr_kind: typing.Optional[types.ExprKind] = Field(default=None, description='Tag naming the concrete expression variant')
    literal_value: typing.Optional["LiteralValue"] = Field(default=None, description='Payload for literal expressions')
    ref_name: typing.Optional[str] = Field(default=None, description='Binding name for REF expressions')
    task_ref_name: typing.Optional[str] = Field(default=None, description='Task-handle name for TASK_REF expressions')
    object_fields: typing.Optional[typing.List["ObjectField"]] = Field(default=None, description='Named fields for OBJECT expressions')
    list_values: typing.Optional[typing.List["ExprNode"]] = Field(default=None, description='Ordered elements for LIST expressions')
    lhs_expr: typing.Optional["ExprNode"] = Field(default=None, description='Left operand for comparison or logical expressions')
    rhs_expr: typing.Optional["ExprNode"] = Field(default=None, description='Right operand for comparison or logical expressions')
    comparison_operator: typing.Optional[types.ComparisonOperator] = Field(default=None, description='Operator for COMPARISON expressions')
    logical_operator: typing.Optional[types.LogicalOperator] = Field(default=None, description='Operator for LOGICAL expressions')
    unary_operator: typing.Optional[types.UnaryOperator] = Field(default=None, description='Operator for UNARY expressions')
    operand_expr: typing.Optional["ExprNode"] = Field(default=None, description='Operand for UNARY expressions')

class LiteralValue(BaseModel):
    # LiteralValue
    # 
    # Purpose
    # -------
    # Represents one atomic literal value carried by a literal expression node.
    # 
    # Fields
    # ------
    # - string_value: string literal, if present.
    # - int_value: integer literal, if present.
    # - float_value: floating-point literal, if present.
    # - bool_value: boolean literal, if present.
    # - is_null: true when the literal value is null.
    # 
    # Invariants
    # ----------
    # - Exactly one of string_value, int_value, float_value, bool_value, or
    # is_null=true should represent the active literal payload.
    # 
    # Notes
    # -----
    # Host code should validate that the emitted literal is unambiguous before
    # converting it into the runtime Literal node.

    string_value: typing.Optional[str] = Field(default=None, description='String literal payload if present')
    int_value: typing.Optional[int] = Field(default=None, description='Integer literal payload if present')
    float_value: typing.Optional[float] = Field(default=None, description='Floating-point literal payload if present')
    bool_value: typing.Optional[bool] = Field(default=None, description='Boolean literal payload if present')
    is_null: typing.Optional[bool] = Field(default=None, description='True when the literal value is null')

class LlmFunctionDescriptor(BaseModel):
    # LlmFunctionDescriptor
    # 
    # Purpose
    # -------
    # Describes one registered LLM-backed function available to the REPL
    # runtime.
    # 
    # Fields
    # ------
    # - function_name: registry-visible BAML function name.
    # - description: concise description of the function's purpose.
    # - argument_contract: optional summary of accepted structured arguments.
    # - returns_child_program: true when this function is intended for
    # RecursiveCallStep use and should return a child program.
    # 
    # Invariants
    # ----------
    # - returns_child_program should be true only for functions that the host
    # runtime can safely use for recursive child-program generation.
    # 
    # Notes
    # -----
    # This descriptor lets the root planner distinguish plain model-backed
    # value calls from recursive subprogram generators.

    function_name: typing.Optional[str] = Field(default=None, description='Runtime registry name of the LLM function')
    description: typing.Optional[str] = Field(default=None, description='Concise description of the function purpose')
    argument_contract: typing.Optional[str] = Field(default=None, description='Optional summary of accepted structured arguments')
    returns_child_program: typing.Optional[bool] = Field(default=None, description='Whether the function returns a child program')

class ObjectField(BaseModel):
    # ObjectField
    # 
    # Purpose
    # -------
    # Represents one named field within a structured object expression.
    # 
    # Fields
    # ------
    # - field_name: field key name.
    # - value_expr: nested expression for the field value.
    # 
    # Invariants
    # ----------
    # - Field names should be unique within the containing object.
    # 
    # Notes
    # -----
    # This helper type exists because the root BAML contract uses tagged nodes
    # instead of recursive union aliases.

    field_name: typing.Optional[str] = Field(default=None, description='Object field key name')
    value_expr: typing.Optional["ExprNode"] = Field(default=None, description='Expression for the field value')

class ProgramMetadataEntry(BaseModel):
    # ProgramMetadataEntry
    # 
    # Purpose
    # -------
    # Represents one lightweight metadata key/value pair attached to an emitted
    # RLM program.
    # 
    # Fields
    # ------
    # - key: metadata key name.
    # - value: metadata value as a compact string.
    # 
    # Invariants
    # ----------
    # - Metadata should remain lightweight and should not duplicate full task
    # context.
    # 
    # Notes
    # -----
    # This mirrors the host runtime's program metadata in a bounded form that is
    # easy for the planner to emit reliably.

    key: typing.Optional[str] = Field(default=None, description='Metadata key name')
    value: typing.Optional[str] = Field(default=None, description='Compact metadata value')

class Resume(BaseModel):
    name: typing.Optional[str] = None
    email: typing.Optional[str] = None
    experience: typing.List[str]
    skills: typing.List[str]

class RlmProgram(BaseModel):
    # RlmProgram
    # 
    # Purpose
    # -------
    # Represents the top-level executable REPL program emitted by the root
    # planner.
    # 
    # Fields
    # ------
    # - steps: ordered executable step list.
    # - metadata: optional lightweight metadata entries for tracing or planner
    # annotations.
    # 
    # Invariants
    # ----------
    # - steps should be emitted in execution order.
    # 
    # Notes
    # -----
    # Metadata is intentionally lightweight here and should stay compact.

    steps: typing.List["StepNode"] = Field(description='Ordered executable step list')
    metadata: typing.Optional[typing.List["ProgramMetadataEntry"]] = Field(default=None, description='Optional lightweight planner metadata')

class RootObservation(BaseModel):
    # RootObservation
    # 
    # Purpose
    # -------
    # Represents one host-generated observation fed back into the next root RLM
    # planning turn.
    # 
    # Fields
    # ------
    # - observation_kind: category of the observation.
    # - summary: compact natural-language or structured summary of what
    # happened.
    # - error_code: optional native runtime error code when execution failed.
    # - error_message: optional native runtime error message when execution
    # failed.
    # - did_return: optional flag indicating whether a program terminated via
    # return.
    # - return_value_summary: optional compact summary of the returned value.
    # - changed_bindings: optional list of updated bindings after execution.
    # - active_task_names: optional list of task-handle names still active after
    # execution.
    # 
    # Invariants
    # ----------
    # - error_code and error_message should be populated together for error
    # observations.
    # 
    # Notes
    # -----
    # Host code should keep this object compact and planner-useful rather than
    # dumping full runtime state or large documents back into context.

    observation_kind: typing.Optional[types.ObservationKind] = Field(default=None, description='Category of the host observation')
    summary: typing.Optional[str] = Field(default=None, description='Compact summary of what happened')
    error_code: typing.Optional[str] = Field(default=None, description='Native runtime error code when execution failed')
    error_message: typing.Optional[str] = Field(default=None, description='Native runtime error message when execution failed')
    did_return: typing.Optional[bool] = Field(default=None, description='Whether the program terminated via return')
    return_value_summary: typing.Optional[str] = Field(default=None, description='Compact summary of the returned value')
    changed_bindings: typing.Optional[typing.List["BindingSnapshot"]] = Field(default=None, description='Updated bindings after execution')
    active_task_names: typing.Optional[typing.List[str]] = Field(default=None, description='Spawned task handles still active after execution')

class RootRlmRequest(BaseModel):
    # RootRlmRequest
    # 
    # Purpose
    # -------
    # Represents the full planner-visible state for one root RLM loop turn.
    # 
    # Fields
    # ------
    # - user_text: raw user task text for the current session or turn.
    # - attachments: task-relevant attachment metadata and references.
    # - current_bindings: compact summaries of bindings currently visible to the
    # runtime.
    # - observation_history: compact host-generated observations from earlier
    # loop iterations.
    # - available_tools: deterministic host tools available to the emitted
    # program.
    # - available_llm_functions: registered LLM-backed functions available to
    # the emitted program.
    # - dsl_summary: concise explanation of the REPL language surface and usage
    # constraints.
    # - planner_instructions: optional host-provided extra instructions for this
    # run.
    # - budget: current iteration and recursion budget snapshot.
    # 
    # Invariants
    # ----------
    # - The request should contain enough information for the planner to choose
    # one bounded next action without inventing unavailable tools or bindings.
    # 
    # Notes
    # -----
    # Host code is responsible for keeping this request compact and relevant.

    user_text: typing.Optional[str] = Field(default=None, description='Raw user task text for the current session or turn')
    attachments: typing.List["AttachmentInput"] = Field(description='Task-relevant attachment metadata and references')
    current_bindings: typing.List["BindingSnapshot"] = Field(description='Compact summaries of current runtime bindings')
    observation_history: typing.List["RootObservation"] = Field(description='Prior host observations from earlier loop iterations')
    available_tools: typing.List["ToolDescriptor"] = Field(description='Deterministic host tools available to the program')
    available_llm_functions: typing.List["LlmFunctionDescriptor"] = Field(description='Registered LLM-backed functions available to the program')
    dsl_summary: typing.Optional[str] = Field(default=None, description='Concise summary of the REPL DSL surface and constraints')
    planner_instructions: typing.Optional[str] = Field(default=None, description='Optional extra host instructions for this run')
    budget: typing.Optional["RuntimeBudgetSnapshot"] = Field(default=None, description='Current iteration and recursion budget snapshot')

class RootRlmResponse(BaseModel):
    # RootRlmResponse
    # 
    # Purpose
    # -------
    # Represents the root planner's next-turn decision for the RLM controller
    # loop.
    # 
    # Fields
    # ------
    # - decision_kind: top-level planner choice for this turn.
    # - program: emitted program when decision_kind=RUN_PROGRAM.
    # - final_answer: final user-facing answer when decision_kind=FINAL_ANSWER.
    # - clarification_question: follow-up question when
    # decision_kind=CLARIFICATION.
    # - planner_notes: optional compact planner note for host logs or tracing.
    # 
    # Invariants
    # ----------
    # - RUN_PROGRAM requires program.
    # - FINAL_ANSWER requires final_answer.
    # - CLARIFICATION requires clarification_question.
    # 
    # Notes
    # -----
    # Host code should validate the selected branch before acting on the
    # response.

    decision_kind: typing.Optional[types.RootDecisionKind] = Field(default=None, description='Top-level planner choice for this turn')
    program: typing.Optional["RlmProgram"] = Field(default=None, description='Program to run when decision_kind is RUN_PROGRAM')
    final_answer: typing.Optional[str] = Field(default=None, description='Final user-facing answer when decision_kind is FINAL_ANSWER')
    clarification_question: typing.Optional[str] = Field(default=None, description='Follow-up question when decision_kind is CLARIFICATION')
    planner_notes: typing.Optional[str] = Field(default=None, description='Optional compact planner note for logs or tracing')

class RuntimeBudgetSnapshot(BaseModel):
    # RuntimeBudgetSnapshot
    # 
    # Purpose
    # -------
    # Captures the current recursion and iteration budget visible to the root
    # planner.
    # 
    # Fields
    # ------
    # - current_recursive_depth: current runtime recursive depth.
    # - max_recursive_depth: configured maximum recursive depth.
    # - recursive_calls_used: total recursive calls already consumed.
    # - max_recursive_calls: configured maximum recursive calls allowed.
    # - iteration_index: current outer-loop iteration index.
    # - max_iterations: maximum outer-loop iterations allowed.
    # 
    # Invariants
    # ----------
    # - Used values should never exceed configured maximums in normal host
    # operation.
    # 
    # Notes
    # -----
    # This snapshot helps the planner choose bounded next actions and avoid
    # wasteful recursion.

    current_recursive_depth: typing.Optional[int] = Field(default=None, description='Current recursive depth in the runtime')
    max_recursive_depth: typing.Optional[int] = Field(default=None, description='Configured maximum recursive depth')
    recursive_calls_used: typing.Optional[int] = Field(default=None, description='Total recursive calls already consumed')
    max_recursive_calls: typing.Optional[int] = Field(default=None, description='Configured maximum recursive calls allowed')
    iteration_index: typing.Optional[int] = Field(default=None, description='Current outer-loop iteration index')
    max_iterations: typing.Optional[int] = Field(default=None, description='Maximum outer-loop iterations allowed')

class StepNode(BaseModel):
    # StepNode
    # 
    # Purpose
    # -------
    # Represents one tagged executable step node in the root planner's BAML
    # mirror of the REPL DSL.
    # 
    # Fields
    # ------
    # - step_kind: concrete step variant tag.
    # - tool_name: tool registry key for TOOL_CALL steps.
    # - args_object: structured argument object for TOOL_CALL, LLM_CALL, and
    # RECURSIVE_CALL steps.
    # - binding_target: destination binding for result-producing steps.
    # - condition_expr: condition for IF steps.
    # - then_steps: true branch body for IF steps.
    # - else_steps: false branch body for IF steps.
    # - iterable_expr: iterable expression for FOREACH steps.
    # - loop_var_name: loop variable name for FOREACH steps.
    # - body_steps: loop body for FOREACH steps.
    # - value_expr: returned or assigned expression for RETURN and ASSIGNMENT
    # steps.
    # - baml_func_name: LLM function name for LLM_CALL and RECURSIVE_CALL steps.
    # - sub_program: child program for SPAWN steps.
    # - join_task_ref_names: task-handle names for JOIN steps.
    # 
    # Invariants
    # ----------
    # - step_kind determines which payload fields should be populated.
    # 
    # Notes
    # -----
    # Host code should validate consistency between step_kind and populated
    # fields before translating to the Python AST.

    step_kind: typing.Optional[types.StepKind] = Field(default=None, description='Tag naming the concrete step variant')
    tool_name: typing.Optional[str] = Field(default=None, description='Tool registry key for TOOL_CALL steps')
    args_object: typing.Optional[typing.List["ObjectField"]] = Field(default=None, description='Structured argument object for call steps')
    binding_target: typing.Optional[str] = Field(default=None, description='Binding that should receive the step result')
    condition_expr: typing.Optional["ExprNode"] = Field(default=None, description='Condition expression for IF steps')
    then_steps: typing.Optional[typing.List["StepNode"]] = Field(default=None, description='Steps to run when the IF condition is true')
    else_steps: typing.Optional[typing.List["StepNode"]] = Field(default=None, description='Steps to run when the IF condition is false')
    iterable_expr: typing.Optional["ExprNode"] = Field(default=None, description='Iterable expression for FOREACH steps')
    loop_var_name: typing.Optional[str] = Field(default=None, description='Loop variable name for FOREACH steps')
    body_steps: typing.Optional[typing.List["StepNode"]] = Field(default=None, description='Body steps for FOREACH steps')
    value_expr: typing.Optional["ExprNode"] = Field(default=None, description='Expression used by RETURN or ASSIGNMENT steps')
    baml_func_name: typing.Optional[str] = Field(default=None, description='LLM function name for LLM or recursive calls')
    sub_program: typing.Optional["RlmProgram"] = Field(default=None, description='Child program to spawn concurrently')
    join_task_ref_names: typing.Optional[typing.List[str]] = Field(default=None, description='Task-handle names to join')

class ToolDescriptor(BaseModel):
    # ToolDescriptor
    # 
    # Purpose
    # -------
    # Describes one deterministic host tool available to the REPL runtime.
    # 
    # Fields
    # ------
    # - tool_name: registry-visible tool name.
    # - description: concise description of behavior and intended use.
    # - argument_contract: optional summary of accepted structured arguments.
    # 
    # Invariants
    # ----------
    # - tool_name should match the actual runtime registry key used by host
    # execution.
    # 
    # Notes
    # -----
    # The planner should rely on these descriptors instead of inventing tool
    # names or argument shapes.

    tool_name: typing.Optional[str] = Field(default=None, description='Runtime registry name of the tool')
    description: typing.Optional[str] = Field(default=None, description='Concise description of tool behavior')
    argument_contract: typing.Optional[str] = Field(default=None, description='Optional summary of accepted structured arguments')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
