# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.AttachmentInput": types.AttachmentInput,
    "stream_types.AttachmentInput": stream_types.AttachmentInput,

    "types.BindingSnapshot": types.BindingSnapshot,
    "stream_types.BindingSnapshot": stream_types.BindingSnapshot,

    "types.ExprNode": types.ExprNode,
    "stream_types.ExprNode": stream_types.ExprNode,

    "types.LiteralValue": types.LiteralValue,
    "stream_types.LiteralValue": stream_types.LiteralValue,

    "types.LlmFunctionDescriptor": types.LlmFunctionDescriptor,
    "stream_types.LlmFunctionDescriptor": stream_types.LlmFunctionDescriptor,

    "types.ObjectField": types.ObjectField,
    "stream_types.ObjectField": stream_types.ObjectField,

    "types.ProgramMetadataEntry": types.ProgramMetadataEntry,
    "stream_types.ProgramMetadataEntry": stream_types.ProgramMetadataEntry,

    "types.Resume": types.Resume,
    "stream_types.Resume": stream_types.Resume,

    "types.RlmProgram": types.RlmProgram,
    "stream_types.RlmProgram": stream_types.RlmProgram,

    "types.RootObservation": types.RootObservation,
    "stream_types.RootObservation": stream_types.RootObservation,

    "types.RootRlmRequest": types.RootRlmRequest,
    "stream_types.RootRlmRequest": stream_types.RootRlmRequest,

    "types.RootRlmResponse": types.RootRlmResponse,
    "stream_types.RootRlmResponse": stream_types.RootRlmResponse,

    "types.RuntimeBudgetSnapshot": types.RuntimeBudgetSnapshot,
    "stream_types.RuntimeBudgetSnapshot": stream_types.RuntimeBudgetSnapshot,

    "types.StepNode": types.StepNode,
    "stream_types.StepNode": stream_types.StepNode,

    "types.ToolDescriptor": types.ToolDescriptor,
    "stream_types.ToolDescriptor": stream_types.ToolDescriptor,


    "types.ComparisonOperator": types.ComparisonOperator,

    "types.ExprKind": types.ExprKind,

    "types.LogicalOperator": types.LogicalOperator,

    "types.ObservationKind": types.ObservationKind,

    "types.RootDecisionKind": types.RootDecisionKind,

    "types.StepKind": types.StepKind,

    "types.UnaryOperator": types.UnaryOperator,

}